/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        WordChoser wChoser = new WordChoser();
        Game game = new Game(wChoser);

        System.out.println("Welcome! Today the word to guess is:");


        do {
            System.out.println(game.getWordToGuess());
            System.out.println("Enter one letter to guess:");
            Scanner scanner = new Scanner(System.in);
            Character guess = scanner.nextLine().charAt(0);
            Boolean result = game.guessLetter(guess);
            Boolean isGameWon = game.isGameWon();

            if (result) {
                if (isGameWon) {
                    System.out.println("Yeaaah! You won!");

                    break;
                }
            } else {
                    System.out.println("Wrong! Remaining attempts:");
                    System.out.println(game.getRemainingAttempts());
                }
        } while (!game.isGameLost()) ;
}
}
